ALTER TABLE classes ADD COLUMN IF NOT EXISTS academic_year TEXT NOT NULL DEFAULT '2025/2026';
ALTER TABLE classes ADD COLUMN IF NOT EXISTS level TEXT NOT NULL DEFAULT 'OTHER';
ALTER TABLE classes ADD COLUMN IF NOT EXISTS stream TEXT NOT NULL DEFAULT 'General';
ALTER TABLE classes ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE subjects ADD COLUMN IF NOT EXISTS department TEXT;
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS subject_teacher TEXT;
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS assigned_class_ids JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS academic_year TEXT NOT NULL DEFAULT '2025/2026';
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS term_name TEXT;
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;