ALTER TABLE grades ADD COLUMN IF NOT EXISTS academic_year TEXT NOT NULL DEFAULT '2025/2026';
ALTER TABLE grades ADD COLUMN IF NOT EXISTS project_score DOUBLE PRECISION;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS assignment_score DOUBLE PRECISION;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS approval_status TEXT NOT NULL DEFAULT 'DRAFT';
ALTER TABLE grades ADD COLUMN IF NOT EXISTS approved_by TEXT;
ALTER TABLE grades ADD COLUMN IF NOT EXISTS approved_at TEXT;

CREATE TABLE IF NOT EXISTS grading_schemes (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  academic_year TEXT NOT NULL,
  ca_weight DOUBLE PRECISION NOT NULL,
  exam_weight DOUBLE PRECISION NOT NULL,
  project_weight DOUBLE PRECISION NOT NULL DEFAULT 0,
  assignment_weight DOUBLE PRECISION NOT NULL DEFAULT 0,
  bands JSONB NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TEXT NOT NULL,
  tenant_id TEXT NOT NULL DEFAULT 'default'
);